### ISSUE TITLE
Can't get it to work with FLEx 9.1.18  

### ISSUE THREAD

**Issue by LHayashi** [cdfarrow/flexlibs#11]
Is there a workaround? I can downgrade but there are other issues in 9.1.15. We're in a lab environment and trying to keep everyone using the same version. 

P.S. I am so excited about FLExTools. I have a number of reports I generate using XSLT off of LIFT files primarily but would love to do this directly off the database and look forward to figuring out how.

**Comment by cdfarrow** [comment]
Hi, FlexTools 2.1.2 generally works with Flex 9.1.18. Please run the _debug batch file and send the log to flextoolshelp[a]gmail.com with any other relevant information.

FlexTools should make it easy to write your reports.

**Comment by LHayashi** [comment]
Sorry about that. I see that it works now. I thought I had done that update
on the machine already. Works well!
