### ISSUE TITLE
FlexTools crashes with exception loading Newtonsoft.json.dll

### ISSUE THREAD

**Issue by makerling** [cdfarrow/flexlibs#2]
FlexTools crashes when run with FLEx 9.0.8+ installed. Happens in both x86 and x64 versions. 

> Error opening project: File not found error: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

In FLEx 9.0.8+ the Newtonsof.Json is version 12.0.3. Apparently .NET binds versions at FLEx build time, so .config binding redirects are used in cases where dependencies still reference an older version of something. Need to find a way to override the the version native to python. 

More details at: [jira.sil.org/browse/LT-20259](url)

**Comment by cdfarrow** [comment]
Issue addressed by including version 11 of Newtonsoft.JSON.dll with flexlibs.
