### ISSUE TITLE
[Feature Request]: Build URL to Text from GUID.

### ISSUE THREAD

**Issue by MattGyverLee** [cdfarrow/flexlibs#9]
I'm not set up for debugging this, but I'd like to see the FLExTools functionality of linking to an interlinear text (which FLEx already supports). I think this code is all that is required.

Can you add this at line 475 between Analyses and lexiconEdit in the BuildGotoURL() function?

```
elif object.ClassID in (TextTags.kClassId):
     tool = u"interlinearEdit";
```

https://github.com/cdfarrow/flexlibs/blob/2267878e99687523a008b868b3585d1fda986e82/flexlibs/code/FLExProject.py#L471-L477

Here's my reference for IDs:
https://github.com/sillsdev/FieldWorks/blob/4d8f17146bb8b1682f8ef80aa639e1b79789fe34/Src/xWorks/LinkListener.cs#L459-L461

**Comment by cdfarrow** [comment]
Thanks for doing the research--that made it much easier to make this change :-) It is available in flexlibs 1.1.6. Use `py -m pip install flexlibs==1.1.6` with the appropriate py version number for your installation if needed.
